/**
 * @file Types.h
 * @author Kishalay Kundu <kishalay.kundu@gmail.com>
 * @section LICENSE
 * See LICENSE.txt included in this package
 *
 * @section DESCRIPTION
 * Enum classes used by the Canvas simulate system. Types.h is
 * automatically generated by the generateEnums program based on
 * input in Assets/Config/EnumTypes.xml.
 */


namespace Sim {

	 enum class ManagerType {
		EventManager,
		GpuManager,
		HpcManager,
		TaskManager,
		PluginManager,
		AssetManager
	 };

	 enum class GpuManagerType {
		OglManager,
		VkManager,
		DxManager
	 };

	 enum class HpcManagerType {
		CudaManager,
		OclManager,
		CpuManager
	 };

	 enum class TaskManagerType {
		TbbManager,
		ThreadManager
	 };

	 enum class PluginType {
		Rigid,
		CpuMsd,
		CudaMsd,
		OclMsd,
		ComputeMsd,
		CpuXfem,
		CudaXfem,
		OclXfem,
		ComputeXfem
	 };

	 enum class AssetType {
		LeftKidney,
		RightKidney,
		GallBladder,
		Liver,
		Scalpel,
		Retractor,
		Apple,
		Melon,
		Cube
	 };

	 enum class ComponentType {
		Geometry,
		Graphics,
		Physics,
		Collision,
		Intersection
	 };

}
