/**
 * @file Event.h
 * @author Kishalay Kundu <kishalay.kundu@gmail.com>
 * @section LICENSE
 * See LICENSE.txt included in this package
 *
 * @section DESCRIPTION
 * The interface to an event in the Chimera system. This is further
 * defined by derived classes for specific event types. Note that the
 * driver/app layer should have access to all types of events that can
 * be generated by the whole system.
 */
#pragma once

#include "Assets/Asset.h"

namespace Sim {

	enum class EventType {
		EVENT_INTERSECTION,
		EVENT_PHYSICS,
		EVENT_COLLISION,
		EVENT_RENDER,
		EVENT_INVALID
	};

	class Event {

		public:
			unsigned int _assetId = 0;
			EventType _eventId = EventType::EVENT_INVALID;

		public:
			Event () = default;
			~Event () = default;

			Event (const Event&) = default;
			Event& operator = (const Event&) = default;

			Event (unsigned int id, EventType ev): _assetId (id), _eventId (ev) {}

			inline EventType GetEventType () const {return _eventId;}
			inline unsigned int GetAssetId () const {return _assetId;}
	};
}

